# Generated by Django 3.0.8 on 2021-12-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('position', models.CharField(choices=[('Front_end', 'Front_end'), ('Back_end', 'Back_end')], max_length=20)),
                ('vote_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
